// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import io "io"
import master "github.com/kmacmcfarlane/go-scheduler/gen/protobuf/master"
import mock "github.com/stretchr/testify/mock"

// MasterClientFactory is an autogenerated mock type for the MasterClientFactory type
type MasterClientFactory struct {
	mock.Mock
}

// CreateClient provides a mock function with given fields: host
func (_m *MasterClientFactory) CreateClient(host string) (master.MasterClient, io.Closer, error) {
	ret := _m.Called(host)

	var r0 master.MasterClient
	if rf, ok := ret.Get(0).(func(string) master.MasterClient); ok {
		r0 = rf(host)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(master.MasterClient)
		}
	}

	var r1 io.Closer
	if rf, ok := ret.Get(1).(func(string) io.Closer); ok {
		r1 = rf(host)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(io.Closer)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(host)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
